language: python
python:
<<<<<<< HEAD
  - "2.7"

install:
    #removing unwanted packages
    - sudo apt-get remove --purge -y $(< unwanted_packages)
    # update aptitude
    - sudo apt-get update -y
    - sudo apt-get install aptitude -y
=======
  - "2.6"
  - "2.7"

install:
    # update aptitude
    - sudo apt-get update -y
>>>>>>> 15fe862f59c98214949ddc295ea2b9b5662cf398

    # install aptitude packages
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)

<<<<<<< HEAD
    - sudo apt-get autoremove -y

    - df -h

=======
>>>>>>> 15fe862f59c98214949ddc295ea2b9b5662cf398
    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

<<<<<<< HEAD
    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import numpy; print(os.path.dirname(numpy.__file__))")

    # install python requirements
    - make setup

script:
=======
    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors

    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import thumbor; print(os.path.dirname(thumbor.__file__))")

script:
    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

>>>>>>> 15fe862f59c98214949ddc295ea2b9b5662cf398
    # finally run tests
    - make ci_test

